# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('dob', models.DateField()),
                ('salary', models.IntegerField(blank=True, max_length=10, null=True)),
                ('position', models.CharField(choices=[(1, 'Manager'), (2, 'Asst.Manager'), (3, 'HR'), (4, 'Sr.Developer'), (5, 'Jr.Developer'), (6, 'Hardware Engg'), (7, 'Content writer'), (8, 'cooridinator'), (9, 'Store Keeper'), (10, 'Assistant')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=1)),
                ('is_deleted', models.BooleanField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(null=True)),
            ],
        ),
    ]
