# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Asst.Manager'), (3, 'HR'), (4, 'Sr.Developer'), (5, 'Jr.Developer'), (6, 'Hardware Engg'), (7, 'Content writer'), (8, 'cooridinator'), (9, 'Store Keeper'), (10, 'Assistant')]),
        ),
    ]
