# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-10-30 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
